### PR TITLE
Wrote job posting for TLA+ infra/release engineer

### PR DESCRIPTION
**Pull request by ahelwer**
Feedback welcome

### CODE REVIEW

**Review by lemmy — COMMENTED** [review]
+1 to require a BSc: While this role might not focus on theory and algorithms, the nature of TLA+ and its tools requires some theoretical knowledge; not just because it has ties to academia.  Also, we want the candidate to eventually become a TLA+ user -- dogfooding makes for good results.

Perhaps add experience with open-source development (working in the open) to the list of preferred skills?

**Comment by muenchnerkindl** [comment]
Looks good to me.

Should the experience level be "required" or "desired"? Should we mention salary and benefits?

NB: The official spelling of INRIA is "Inria".

**Comment by lemmy** [comment]
Most people from the TLA+ project are located in the American or European time zones.  I'd suggest keeping the number of time zones low.  Related, mentioning benefits and salaries seems difficult unless we commit to specific regions.  How do other companies do this with remote positions?

**Comment by muenchnerkindl** [comment]
Interesting suggestion, but makes sense to me!

**Comment by lemmy** [comment]
@konnov says that IS outsources the problem of prorating salaries and benefits for geographic regions.  Perhaps, we can defer the problem until we change this from an imaginary job ad to a real one once the foundation has been established.  In its current form, a salary range is more of a message to potential foundation members.

Speaking of members, we could incentivize becoming a founding member by giving founders a discount.

**Pull request merged**
